### ISSUE TITLE
"Oh no." ?

### ISSUE THREAD

**Issue by drscotthawley** [gagan3012/keytotext#25]
"Error running app. If this keeps happening, please file an issue."

Ok,...sure?  I know nothing about this app.  

Just saw [your tweet](https://twitter.com/philipvollet/status/1391462248749666308), clicked the link to this repo, then clicked [the link on the side](https://share.streamlit.io/gagan3012/keytotext/UI/app.py).   Got that message.  Now what? 

Chrome browser, Linux.

**Comment by gagan3012** [comment]
Hello, it is fixed now!

**Comment by drscotthawley** [comment]
Confirmed!  Thanks.  Closing.
