### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement keytotext (from versions: none)

### ISSUE THREAD

**Issue by abhijithneilabraham** [gagan3012/keytotext#59]
Hi,

I tried to install keytotext via `pip install keytotext --upgrade` in local machine.

but came across the following :
```
ERROR: Could not find a version that satisfies the requirement keytotext (from versions: none)
ERROR: No matching distribution found for keytotext
```

My pip version is the latest. However, the above works just fine in colab. Please guide me through the fix?

**Comment by gagan3012** [comment]
Hello, 
the package name is keytotext
so you can run
```
pip install keytotext
```

**Comment by abhijithneilabraham** [comment]
Sorry, that was a typo when I experimented new names and copied that traceback. Before that, I did try with the original , and still got the same issue. 

```
 pip install keytotext
ERROR: Could not find a version that satisfies the requirement keytotext (from versions: none)
ERROR: No matching distribution found for keytotext

```

@gagan3012  

 I am using MacOS Mojave , if that helps.

**Comment by gagan3012** [comment]
What python version are you using?

**Comment by abhijithneilabraham** [comment]
I'm using 3.6

**Comment by gagan3012** [comment]
Keytotext supports python=>3.7

**Comment by abhijithneilabraham** [comment]
Oh Okay! Thanks a lot.
